"""v1_0 schema

Revision ID: 13ebc5f35728
Revises: 835fd421b370
Create Date: 2024-10-28 11:55:53.811596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13ebc5f35728'
down_revision: Union[str, None] = '835fd421b370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coarses',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coarses_id'), 'coarses', ['id'], unique=False)
    op.create_table('motions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('acceleration_x', sa.Float(), nullable=True),
    sa.Column('acceleration_y', sa.Float(), nullable=True),
    sa.Column('acceleration_z', sa.Float(), nullable=True),
    sa.Column('gyro_x', sa.Float(), nullable=True),
    sa.Column('gyro_y', sa.Float(), nullable=True),
    sa.Column('gyro_z', sa.Float(), nullable=True),
    sa.Column('magnetometer_x', sa.Float(), nullable=True),
    sa.Column('magnetometer_y', sa.Float(), nullable=True),
    sa.Column('magnetometer_z', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('coarse_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coarse_id'], ['coarses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_motions_id'), 'motions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_motions_id'), table_name='motions')
    op.drop_table('motions')
    op.drop_index(op.f('ix_coarses_id'), table_name='coarses')
    op.drop_table('coarses')
    # ### end Alembic commands ###
