"""v1_1

Revision ID: c9b03205f14a
Revises: 13ebc5f35728
Create Date: 2024-10-28 14:12:58.689434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9b03205f14a'
down_revision: Union[str, None] = '13ebc5f35728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index('ix_coarses_id', table_name='coarses')
    #op.drop_table('coarses')
    op.execute("DROP TABLE coarses CASCADE")
    #op.drop_index('ix_motions_id', table_name='motions')
    op.drop_table('DROP TABLE motions CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('acceleration_x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('acceleration_y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('acceleration_z', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gyro_x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gyro_y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gyro_z', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('magnetometer_x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('magnetometer_y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('magnetometer_z', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pressure', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('coarse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['coarse_id'], ['coarses.id'], name='motions_coarse_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='motions_pkey')
    )
    op.create_index('ix_motions_id', 'motions', ['id'], unique=False)
    op.create_table('coarses',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='coarses_pkey')
    )
    op.create_index('ix_coarses_id', 'coarses', ['id'], unique=False)
    # ### end Alembic commands ###
